<?php

namespace App\Services;

/**
 * Services & Pricing data — Founder-approved pricing (Sep 3, 2026).
 *
 * Three categories: Website Design, Automation, Branding.
 * Each has 3-4 tiers with real Naira price ranges.
 */
class PricingService
{
    public function all(): array
    {
        return [
            'website' => [
                'title' => 'Website Design',
                'description' => 'From starter sites to full shops. They work on a phone, they show up on Google, and people can reach you.',
                'tiers' => [
                    [
                        'name' => 'Starter Website',
                        'price' => '₦200,000',
                        'price_range' => '₦200,000 – ₦250,000',
                        'price_note' => 'one-time',
                        'description' => 'A small site so people can find you and get in touch.',
                        'features' => [
                            'Up to 3 pages',
                            'Mobile responsive',
                            'Professional UI design',
                            'Contact/WhatsApp integration',
                            'Basic SEO',
                            'Social media links',
                            '2 revisions',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hi Chada Digital! I would like to build a Starter Website (around ₦200K–₦250K). What are the next steps?',
                        'highlight' => false,
                    ],
                    [
                        'name' => 'Business Website',
                        'price' => '₦300,000',
                        'price_range' => '₦300,000 – ₦450,000',
                        'price_note' => 'one-time',
                        'description' => 'Five to seven pages, a form, and room for the proof you already have.',
                        'features' => [
                            'Up to 5–7 pages',
                            'Custom design',
                            'Mobile responsive',
                            'Contact/WhatsApp integration',
                            'Basic SEO',
                            'Google Analytics',
                            'Testimonials',
                            'FAQ section',
                            'Obvious next step on each page',
                            '3 revisions',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hello! I am interested in the Business Website tier (₦300K–₦450K). Can you walk me through what is included?',
                        'highlight' => true,
                    ],
                    [
                        'name' => 'Premium Website',
                        'price' => '₦500,000',
                        'price_range' => '₦500,000 – ₦750,000+',
                        'price_note' => 'one-time',
                        'description' => 'Bigger sites with extra pages, tracking, and the tools you already pay for plugged in.',
                        'features' => [
                            '7+ pages',
                            'Advanced/custom design',
                            'SEO setup',
                            'Analytics & tracking',
                            'Forms and lead capture',
                            'Third-party integrations',
                            'Advanced functionality',
                            'Clear call-to-action on every page',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hi! I need a Premium Website (₦500K–₦750K+) with advanced functionality. Let us talk scope.',
                        'highlight' => false,
                    ],
                    [
                        'name' => 'E-Commerce Website',
                        'price' => '₦500,000',
                        'price_range' => '₦500,000 – ₦800,000+',
                        'price_note' => 'one-time',
                        'description' => 'Full online store with product catalogue, checkout, and payment integration.',
                        'features' => [
                            'Product catalogue',
                            'Shopping cart',
                            'Checkout',
                            'Paystack/Flutterwave',
                            'Order notifications',
                            'Customer management',
                            'Works on phones',
                            'Basic SEO',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hello Chada Digital! I want to set up an E-Commerce store (₦500K–₦800K+). What do you need from me to start?',
                        'highlight' => false,
                    ],
                ],
            ],
            'automation' => [
                'title' => 'Automation',
                'description' => 'Forms, WhatsApp pings, and follow-ups that keep running after you close the laptop.',
                'tiers' => [
                    [
                        'name' => 'Starter Automation',
                        'price' => '₦150,000',
                        'price_range' => '₦150,000 – ₦200,000',
                        'price_note' => 'one-time',
                        'description' => 'A single automated workflow to capture and route leads.',
                        'features' => [
                            'One workflow',
                            'Form → email/WhatsApp',
                            'Google Sheets integration',
                            'Basic notifications',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hi! I need a Starter Automation workflow (₦150K–₦200K) for lead capture. What information do you need?',
                        'highlight' => false,
                    ],
                    [
                        'name' => 'Business Automation',
                        'price' => '₦250,000',
                        'price_range' => '₦250,000 – ₦400,000',
                        'price_note' => 'one-time',
                        'description' => 'Multiple interconnected workflows with CRM and follow-up automation.',
                        'features' => [
                            'Multiple workflows',
                            'CRM integration',
                            'WhatsApp/email automation',
                            'Lead capture',
                            'Follow-up automation',
                            'Notifications',
                            'Basic reporting',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hello! I am looking at the Business Automation package (₦250K–₦400K) with CRM and follow-up sequences. Can we schedule a call?',
                        'highlight' => true,
                    ],
                    [
                        'name' => 'Advanced Automation',
                        'price' => '₦500,000+',
                        'price_range' => '₦500,000+',
                        'price_note' => 'one-time',
                        'description' => 'Several workflows talking to each other, plus the odd extra step if it actually helps.',
                        'features' => [
                            'Multiple interconnected workflows',
                            'CRM',
                            'AI integration',
                            'WhatsApp automation',
                            'Payment integration',
                            'Lead qualification',
                            'Automated follow-up',
                            'Custom business processes',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hi Chada Digital! I need Advanced Automation (₦500K+) with AI integration and custom workflows. Let us discuss.',
                        'highlight' => false,
                    ],
                ],
            ],
            'branding' => [
                'title' => 'Branding',
                'description' => 'A logo and a look you can use on the site, Instagram, and a business card.',
                'tiers' => [
                    [
                        'name' => 'Starter Branding',
                        'price' => '₦100,000',
                        'price_range' => '₦100,000 – ₦150,000',
                        'price_note' => 'one-time',
                        'description' => 'The essentials: logo, colours, and typography.',
                        'features' => [
                            'Logo',
                            'Colour palette',
                            'Typography',
                            'Basic brand direction',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hello! I want to start with the Starter Branding package (₦100K–₦150K) for a logo and colour palette. What is the process?',
                        'highlight' => false,
                    ],
                    [
                        'name' => 'Business Branding',
                        'price' => '₦200,000',
                        'price_range' => '₦200,000 – ₦300,000',
                        'price_note' => 'one-time',
                        'description' => 'A complete brand package with guidelines and marketing collateral.',
                        'features' => [
                            'Logo',
                            'Colour palette',
                            'Typography',
                            'Brand guidelines',
                            'Social media templates',
                            'Business card',
                            'Letterhead',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hi! I am interested in the Business Branding package (₦200K–₦300K) with full guidelines and templates. Can we talk?',
                        'highlight' => true,
                    ],
                    [
                        'name' => 'Complete Brand Identity',
                        'price' => '₦350,000+',
                        'price_range' => '₦350,000+',
                        'price_note' => 'one-time',
                        'description' => 'Full visual identity system with all marketing materials and stationery.',
                        'features' => [
                            'Full visual identity',
                            'Logo system',
                            'Brand guidelines',
                            'Social media templates',
                            'Marketing materials',
                            'Business stationery',
                        ],
                        'cta' => 'Chat on WhatsApp',
                        'whatsapp_message' => 'Hello Chada Digital! I need a Complete Brand Identity (₦350K+) including logo system, guidelines, and stationery. Can we talk through it?',
                        'highlight' => false,
                    ],
                ],
            ],
        ];
    }
}
